/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SeminarioForms;

import Servicios.conectar;
import entidades.Productos;
import entidades.Proveedores;
import entidades.stock;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario Dell
 */
public class Bodega extends javax.swing.JFrame {

    conectar cc=new conectar();
    Connection cn=cc.Conexionn();
    Productos prods=new Productos();
    stock prodss=new stock();
    Proveedores provs=new Proveedores();
    
    
    /**
     * Creates new form Inventoarios
     */
    public Bodega() {
        initComponents();
        Cargar_P();
        Cargar_P2();
        Cargar_P3();
        Cargar_P4();
         this.setLocationRelativeTo(null);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p4 = new javax.swing.JTabbedPane();
        panel_alimento = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        panel_panaderia = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtidprod0 = new javax.swing.JTextField();
        txtname0 = new javax.swing.JTextField();
        txtfv0 = new com.toedter.calendar.JDateChooser();
        foto_panaderia = new javax.swing.JLabel();
        Imagen = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        cmbprov1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtipanaderia = new javax.swing.JButton();
        txtcant0 = new javax.swing.JSpinner();
        jLabel20 = new javax.swing.JLabel();
        txtprecio0 = new javax.swing.JTextField();
        panel_panaderia1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtidprod1 = new javax.swing.JTextField();
        txtname1 = new javax.swing.JTextField();
        txtfv1 = new com.toedter.calendar.JDateChooser();
        foto_panaderia1 = new javax.swing.JLabel();
        Imagen1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        cmbprov2 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtlacteos = new javax.swing.JButton();
        txtcant1 = new javax.swing.JSpinner();
        jLabel27 = new javax.swing.JLabel();
        txtprecio1 = new javax.swing.JTextField();
        panel_panaderia2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txtidprod2 = new javax.swing.JTextField();
        txtname2 = new javax.swing.JTextField();
        txtfv2 = new com.toedter.calendar.JDateChooser();
        foto_panaderia2 = new javax.swing.JLabel();
        Imagen2 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        cmbprov3 = new javax.swing.JComboBox<>();
        jLabel31 = new javax.swing.JLabel();
        txttienda = new javax.swing.JButton();
        txtcant2 = new javax.swing.JSpinner();
        jLabel32 = new javax.swing.JLabel();
        txtprecio2 = new javax.swing.JTextField();
        panel_panaderia3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtidprod3 = new javax.swing.JTextField();
        txtname3 = new javax.swing.JTextField();
        txtfv3 = new com.toedter.calendar.JDateChooser();
        foto_panaderia3 = new javax.swing.JLabel();
        Imagen3 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        cmbprov4 = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        txtipanaderia1 = new javax.swing.JButton();
        txtcant3 = new javax.swing.JSpinner();
        jLabel21 = new javax.swing.JLabel();
        txtprecio3 = new javax.swing.JTextField();
        btnsalir = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btninventario = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        p4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 102, 0), new java.awt.Color(255, 102, 0), new java.awt.Color(255, 102, 0), new java.awt.Color(255, 102, 0)));

        panel_alimento.setBackground(new java.awt.Color(204, 204, 204));
        panel_alimento.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Tipo de alimento"));

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel10.setText("Bodega");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Bodega.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PlatodeComida830.jpg"))); // NOI18N

        javax.swing.GroupLayout panel_alimentoLayout = new javax.swing.GroupLayout(panel_alimento);
        panel_alimento.setLayout(panel_alimentoLayout);
        panel_alimentoLayout.setHorizontalGroup(
            panel_alimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_alimentoLayout.createSequentialGroup()
                .addGap(344, 344, 344)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panel_alimentoLayout.createSequentialGroup()
                .addGap(304, 304, 304)
                .addComponent(jLabel6))
            .addGroup(panel_alimentoLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_alimentoLayout.setVerticalGroup(
            panel_alimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_alimentoLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel6))
            .addGroup(panel_alimentoLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        p4.addTab("Seleccione uno", panel_alimento);

        panel_panaderia.setBackground(new java.awt.Color(204, 204, 204));
        panel_panaderia.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Panaderia"));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Cantidad*:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Idproducto*:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Nombre*:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Fecha de vencimiento* :");

        txtidprod0.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtidprod0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidprod0ActionPerformed(evt);
            }
        });

        txtname0.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        foto_panaderia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Imagen.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Imagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImagenActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Seleccionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cmbprov1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbprov1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        cmbprov1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbprov1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Proveedor*:");

        txtipanaderia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtipanaderia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Icono_nuevo.png"))); // NOI18N
        txtipanaderia.setText("Guardar");
        txtipanaderia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtipanaderiaActionPerformed(evt);
            }
        });

        txtcant0.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("Precio*:");

        txtprecio0.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout panel_panaderiaLayout = new javax.swing.GroupLayout(panel_panaderia);
        panel_panaderia.setLayout(panel_panaderiaLayout);
        panel_panaderiaLayout.setHorizontalGroup(
            panel_panaderiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_panaderiaLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(panel_panaderiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(panel_panaderiaLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel13)))
                .addGap(4, 4, 4)
                .addGroup(panel_panaderiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtidprod0, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtname0, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(138, 138, 138)
                .addComponent(foto_panaderia, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panel_panaderiaLayout.createSequentialGroup()
                .addGap(455, 455, 455)
                .addComponent(Imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panel_panaderiaLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addComponent(txtcant0, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(175, 175, 175)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panel_panaderiaLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel12)
                .addGap(4, 4, 4)
                .addComponent(txtfv0, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panel_panaderiaLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel4)
                .addGap(10, 10, 10)
                .addComponent(cmbprov1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panel_panaderiaLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jLabel20)
                .addGap(10, 10, 10)
                .addComponent(txtprecio0, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panel_panaderiaLayout.createSequentialGroup()
                .addGap(416, 416, 416)
                .addComponent(txtipanaderia, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_panaderiaLayout.setVerticalGroup(
            panel_panaderiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_panaderiaLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(panel_panaderiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_panaderiaLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel11)
                        .addGap(43, 43, 43)
                        .addComponent(jLabel13))
                    .addGroup(panel_panaderiaLayout.createSequentialGroup()
                        .addComponent(txtidprod0, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(txtname0, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_panaderiaLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(foto_panaderia, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addComponent(Imagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(panel_panaderiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_panaderiaLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel1))
                    .addGroup(panel_panaderiaLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(txtcant0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(panel_panaderiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfv0, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(panel_panaderiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_panaderiaLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cmbprov1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(panel_panaderiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_panaderiaLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel20))
                    .addComponent(txtprecio0, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(txtipanaderia, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        p4.addTab("Panadería", panel_panaderia);

        panel_panaderia1.setBackground(new java.awt.Color(204, 204, 204));
        panel_panaderia1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Lácteos"));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Cantidad*:");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setText("Idproducto*:");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setText("Nombre*:");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel26.setText("Fecha de vencimiento* :");

        txtidprod1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtidprod1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidprod1ActionPerformed(evt);
            }
        });

        txtname1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        foto_panaderia1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Imagen1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Imagen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Imagen1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Seleccionar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        cmbprov2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbprov2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        cmbprov2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbprov2ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Proveedor*:");

        txtlacteos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtlacteos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Icono_nuevo.png"))); // NOI18N
        txtlacteos.setText("Guardar");
        txtlacteos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlacteosActionPerformed(evt);
            }
        });

        txtcant1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel27.setText("Precio*:");

        txtprecio1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout panel_panaderia1Layout = new javax.swing.GroupLayout(panel_panaderia1);
        panel_panaderia1.setLayout(panel_panaderia1Layout);
        panel_panaderia1Layout.setHorizontalGroup(
            panel_panaderia1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_panaderia1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(panel_panaderia1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_panaderia1Layout.createSequentialGroup()
                        .addGroup(panel_panaderia1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_panaderia1Layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtfv1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_panaderia1Layout.createSequentialGroup()
                                .addGroup(panel_panaderia1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panel_panaderia1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbprov2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtprecio1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(185, 216, Short.MAX_VALUE))
                    .addGroup(panel_panaderia1Layout.createSequentialGroup()
                        .addGroup(panel_panaderia1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_panaderia1Layout.createSequentialGroup()
                                .addGroup(panel_panaderia1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel25))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panel_panaderia1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtidprod1, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                    .addComponent(txtname1)))
                            .addGroup(panel_panaderia1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtcant1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(panel_panaderia1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_panaderia1Layout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addGroup(panel_panaderia1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Imagen1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(foto_panaderia1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_panaderia1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panel_panaderia1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_panaderia1Layout.createSequentialGroup()
                                        .addComponent(txtlacteos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(91, 91, 91))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_panaderia1Layout.createSequentialGroup()
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(57, 57, 57))))))))
        );
        panel_panaderia1Layout.setVerticalGroup(
            panel_panaderia1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_panaderia1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(panel_panaderia1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_panaderia1Layout.createSequentialGroup()
                        .addGroup(panel_panaderia1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(txtidprod1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(panel_panaderia1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(txtname1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(foto_panaderia1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panel_panaderia1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_panaderia1Layout.createSequentialGroup()
                        .addGap(27, 81, Short.MAX_VALUE)
                        .addGroup(panel_panaderia1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfv1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(panel_panaderia1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbprov2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(panel_panaderia1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(txtprecio1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21))
                    .addGroup(panel_panaderia1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Imagen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_panaderia1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(txtcant1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(txtlacteos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );

        p4.addTab("Lacteos", panel_panaderia1);

        panel_panaderia2.setBackground(new java.awt.Color(204, 204, 204));
        panel_panaderia2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Tienda"));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Cantidad*:");

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel28.setText("Idproducto*:");

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel29.setText("Nombre*:");

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel30.setText("Fecha de vencimiento* :");

        txtidprod2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtidprod2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidprod2ActionPerformed(evt);
            }
        });

        txtname2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        foto_panaderia2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Imagen2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Imagen2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Imagen2ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("Seleccionar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        cmbprov3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbprov3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        cmbprov3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbprov3ActionPerformed(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel31.setText("Proveedor*:");

        txttienda.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txttienda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Icono_nuevo.png"))); // NOI18N
        txttienda.setText("Guardar");
        txttienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttiendaActionPerformed(evt);
            }
        });

        txtcant2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel32.setText("Precio*:");

        txtprecio2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout panel_panaderia2Layout = new javax.swing.GroupLayout(panel_panaderia2);
        panel_panaderia2.setLayout(panel_panaderia2Layout);
        panel_panaderia2Layout.setHorizontalGroup(
            panel_panaderia2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_panaderia2Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(panel_panaderia2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_panaderia2Layout.createSequentialGroup()
                        .addGroup(panel_panaderia2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_panaderia2Layout.createSequentialGroup()
                                .addComponent(jLabel30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtfv2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_panaderia2Layout.createSequentialGroup()
                                .addGroup(panel_panaderia2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel32)
                                    .addComponent(jLabel31))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panel_panaderia2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbprov3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtprecio2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(185, 216, Short.MAX_VALUE))
                    .addGroup(panel_panaderia2Layout.createSequentialGroup()
                        .addGroup(panel_panaderia2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_panaderia2Layout.createSequentialGroup()
                                .addGroup(panel_panaderia2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel29))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panel_panaderia2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtidprod2, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                    .addComponent(txtname2)))
                            .addGroup(panel_panaderia2Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtcant2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(panel_panaderia2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_panaderia2Layout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addGroup(panel_panaderia2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Imagen2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(foto_panaderia2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_panaderia2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panel_panaderia2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_panaderia2Layout.createSequentialGroup()
                                        .addComponent(txttienda, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(91, 91, 91))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_panaderia2Layout.createSequentialGroup()
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(57, 57, 57))))))))
        );
        panel_panaderia2Layout.setVerticalGroup(
            panel_panaderia2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_panaderia2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(panel_panaderia2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_panaderia2Layout.createSequentialGroup()
                        .addGroup(panel_panaderia2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(txtidprod2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(panel_panaderia2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(txtname2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(foto_panaderia2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panel_panaderia2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_panaderia2Layout.createSequentialGroup()
                        .addGap(27, 81, Short.MAX_VALUE)
                        .addGroup(panel_panaderia2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfv2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(panel_panaderia2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbprov3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(panel_panaderia2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32)
                            .addComponent(txtprecio2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21))
                    .addGroup(panel_panaderia2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Imagen2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_panaderia2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(txtcant2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(txttienda, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );

        p4.addTab("Tienda", panel_panaderia2);

        panel_panaderia3.setBackground(new java.awt.Color(204, 204, 204));
        panel_panaderia3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Panaderia"));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Cantidad*:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Idingrediente*:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Nombre*:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Fecha de vencimiento* :");

        txtidprod3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtidprod3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidprod3ActionPerformed(evt);
            }
        });

        txtname3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        foto_panaderia3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Imagen3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Imagen3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Imagen3ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setText("Seleccionar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        cmbprov4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbprov4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        cmbprov4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbprov4ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Proveedor*:");

        txtipanaderia1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtipanaderia1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Icono_nuevo.png"))); // NOI18N
        txtipanaderia1.setText("Guardar");
        txtipanaderia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtipanaderia1ActionPerformed(evt);
            }
        });

        txtcant3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setText("Precio*:");

        txtprecio3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout panel_panaderia3Layout = new javax.swing.GroupLayout(panel_panaderia3);
        panel_panaderia3.setLayout(panel_panaderia3Layout);
        panel_panaderia3Layout.setHorizontalGroup(
            panel_panaderia3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_panaderia3Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(panel_panaderia3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addGroup(panel_panaderia3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel15)))
                .addGap(4, 4, 4)
                .addGroup(panel_panaderia3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtidprod3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtname3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(138, 138, 138)
                .addComponent(foto_panaderia3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panel_panaderia3Layout.createSequentialGroup()
                .addGap(455, 455, 455)
                .addComponent(Imagen3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panel_panaderia3Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jLabel9)
                .addGap(10, 10, 10)
                .addComponent(txtcant3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(175, 175, 175)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panel_panaderia3Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel16)
                .addGap(4, 4, 4)
                .addComponent(txtfv3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panel_panaderia3Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel17)
                .addGap(10, 10, 10)
                .addComponent(cmbprov4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panel_panaderia3Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jLabel21)
                .addGap(10, 10, 10)
                .addComponent(txtprecio3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panel_panaderia3Layout.createSequentialGroup()
                .addGap(416, 416, 416)
                .addComponent(txtipanaderia1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_panaderia3Layout.setVerticalGroup(
            panel_panaderia3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_panaderia3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(panel_panaderia3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_panaderia3Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel14)
                        .addGap(43, 43, 43)
                        .addComponent(jLabel15))
                    .addGroup(panel_panaderia3Layout.createSequentialGroup()
                        .addComponent(txtidprod3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(txtname3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_panaderia3Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(foto_panaderia3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addComponent(Imagen3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(panel_panaderia3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_panaderia3Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel9))
                    .addGroup(panel_panaderia3Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(txtcant3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(panel_panaderia3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfv3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(panel_panaderia3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_panaderia3Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cmbprov4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(panel_panaderia3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_panaderia3Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel21))
                    .addComponent(txtprecio3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(txtipanaderia1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        p4.addTab("Ingredientes", panel_panaderia3);

        btnsalir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnsalir.setText("Salir");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Tienda");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btninventario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btninventario.setText("Inventario");
        btninventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninventarioActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton6.setText("Panadería");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton7.setText("Lácteos");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(p4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(270, 270, 270)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
<<<<<<< HEAD
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(900, 900, 900)
                .addComponent(btninventario, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(920, 920, 920)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(900, 900, 900)
                .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel2)
=======
                    .addComponent(btninventario, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(60, 60, 60))
>>>>>>> a864b7f7262c6d1fbd52be3f45fcee6683907d89
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
<<<<<<< HEAD
                .addGap(70, 70, 70)
                .addComponent(p4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(360, 360, 360)
                .addComponent(btninventario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(410, 410, 410)
                .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel2)
=======
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(p4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(btninventario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(100, 100, 100))
>>>>>>> a864b7f7262c6d1fbd52be3f45fcee6683907d89
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void Cargar_P()
    {
        cmbprov1.removeAllItems();
       
        String  nitprov=provs.getNitproveedor(), nombreprov=provs.getNombreProveedor(), direccion=provs.getDirecion(),c1="";
        int telefono=provs.getTelefono(), activo=provs.getActivo();
            try
                {
                      String sql="select *from proveedores";
                      PreparedStatement pes=cn.prepareStatement(sql);
                      ResultSet raton=pes.executeQuery();
                      while(raton.next())
                      {
                          nitprov=raton.getString("Nitproveedor");nombreprov=raton.getString("NombreProveedor");telefono=raton.getInt("Telefono");direccion=raton.getString("Direccion");
                          
                          c1=""+nitprov;
                           cmbprov1.addItem(c1);
                }
                }catch(Exception e){}
                
    }
public void Cargar_P2()
    {
        cmbprov2.removeAllItems();
       
        String nitprov=provs.getNitproveedor(), nombreprov=provs.getNombreProveedor(), direccion=provs.getDirecion(),c1="";
        int telefono=provs.getTelefono(), activo=provs.getActivo();
            try
                {
                      String sql="select *from proveedores";
                      PreparedStatement pes=cn.prepareStatement(sql);
                      ResultSet raton=pes.executeQuery();
                      while(raton.next())
                      {
                          nitprov=raton.getString("Nitproveedor");nombreprov=raton.getString("NombreProveedor");telefono=raton.getInt("Telefono");direccion=raton.getString("Direccion");
                          c1=""+nitprov;
                          
                           cmbprov2.addItem(c1);
                }
                }catch(Exception e){}
                
    }
public void Cargar_P3()
    {
        cmbprov3.removeAllItems();
       
        String nitprov=provs.getNitproveedor(), nombreprov=provs.getNombreProveedor(), direccion=provs.getDirecion(),c1="";
        int telefono=provs.getTelefono(), activo=provs.getActivo();
            try
                {
                      String sql="select *from proveedores";
                      PreparedStatement pes=cn.prepareStatement(sql);
                      ResultSet raton=pes.executeQuery();
                      while(raton.next())
                      {
                          nitprov=raton.getString("Nitproveedor");nombreprov=raton.getString("NombreProveedor");telefono=raton.getInt("Telefono");direccion=raton.getString("Direccion");
                          c1=""+nitprov;
                          
                           cmbprov3.addItem(c1);
                }
                }catch(Exception e){}
                
    }
public void Cargar_P4()
    {
        cmbprov4.removeAllItems();
       
        String nitprov=provs.getNitproveedor(), nombreprov=provs.getNombreProveedor(), direccion=provs.getDirecion(),c1="";
        int telefono=provs.getTelefono(), activo=provs.getActivo();
            try
                {
                      String sql="select *from proveedores";
                      PreparedStatement pes=cn.prepareStatement(sql);
                      ResultSet raton=pes.executeQuery();
                      while(raton.next())
                      {
                          nitprov=raton.getString("Nitproveedor");nombreprov=raton.getString("NombreProveedor");telefono=raton.getInt("Telefono");direccion=raton.getString("Direccion");
                          c1=""+nitprov;
                          
                           cmbprov4.addItem(c1);
                }
                }catch(Exception e){}
                
    }
   
    
    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        Menu_administrador prin = new  Menu_administrador();
        prin.setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnsalirActionPerformed

    private void txttiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttiendaActionPerformed
        String dia = Integer.toString(txtfv2.getCalendar().get(Calendar.DAY_OF_MONTH));
        String mes = Integer.toString(txtfv2.getCalendar().get(Calendar.MONTH) + 1);
        String year = Integer.toString(txtfv2.getCalendar().get(Calendar.YEAR));
        String fecha = (dia + "/" + mes+ "/" + year);
        String cantidad=txtcant2.getValue().toString();
        String idproducto=txtidprod2.getText(),nombreprod=txtname2.getText();
        int categoria=2,activo=1;
        double precio=Double.parseDouble(txtprecio2.getText());
        String proveedores3=cmbprov3.getSelectedItem().toString();

        try{

            String sql="Insert into productos values ('"+idproducto+"','"+nombreprod+"','"+categoria+"','"+activo+"')";

            PreparedStatement pes=cn.prepareStatement(sql);
            pes.executeUpdate();

            JOptionPane.showMessageDialog(rootPane, "Insertados");
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(rootPane, "NO Insertados");
        }
        try{

            String sql1="Insert into stock values ('"+proveedores3+"','"+idproducto+"','"+cantidad+"','"+fecha+"','"+precio+"')";
            PreparedStatement pes1=cn.prepareStatement(sql1);

            pes1.executeUpdate();
            JOptionPane.showMessageDialog(rootPane, "Insertados");
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(rootPane, "NO Insertados");
        }
    }//GEN-LAST:event_txttiendaActionPerformed

    private void cmbprov3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbprov3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbprov3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void Imagen2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Imagen2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Imagen2ActionPerformed

    private void txtidprod2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidprod2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidprod2ActionPerformed

    private void txtlacteosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlacteosActionPerformed
         String dia = Integer.toString(txtfv1.getCalendar().get(Calendar.DAY_OF_MONTH));
        String mes = Integer.toString(txtfv1.getCalendar().get(Calendar.MONTH) + 1);
        String year = Integer.toString(txtfv1.getCalendar().get(Calendar.YEAR));
        String fecha = (dia + "/" + mes+ "/" + year);
        String cantidad=txtcant1.getValue().toString();
        String idproducto=txtidprod1.getText(),nombreprod=txtname1.getText();
        int categoria=1,activo=1;
        String proveedores2=cmbprov2.getSelectedItem().toString();
        double precio=Double.parseDouble(txtprecio1.getText());

        try{

            String sql="Insert into productos values ('"+idproducto+"','"+nombreprod+"','"+categoria+"','"+activo+"')";

            PreparedStatement pes=cn.prepareStatement(sql);
            pes.executeUpdate();

            JOptionPane.showMessageDialog(rootPane, "Insertados");
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(rootPane, "NO Insertados");
        }
        try{

            String sql1="Insert into stock values ('"+proveedores2+"','"+idproducto+"','"+cantidad+"','"+fecha+"','"+precio+"')";
            PreparedStatement pes1=cn.prepareStatement(sql1);

            pes1.executeUpdate();
            JOptionPane.showMessageDialog(rootPane, "Insertados");
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(rootPane, "NO Insertados");
        }
    }//GEN-LAST:event_txtlacteosActionPerformed

    private void cmbprov2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbprov2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbprov2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Imagen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Imagen1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Imagen1ActionPerformed

    private void txtidprod1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidprod1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidprod1ActionPerformed

    private void txtipanaderiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtipanaderiaActionPerformed

        String dia = Integer.toString(txtfv0.getCalendar().get(Calendar.DAY_OF_MONTH));
        String mes = Integer.toString(txtfv0.getCalendar().get(Calendar.MONTH) + 1);
        String year = Integer.toString(txtfv0.getCalendar().get(Calendar.YEAR));
        String fecha = (year + "-" + mes+ "-" + dia);
        String cantidad=txtcant0.getValue().toString();
        String idproducto=txtidprod0.getText(),nombreprod=txtname0.getText();
        int categoria=1,
        activo=1;
        double precio=Double.parseDouble(txtprecio0.getText());
         String proveedores=cmbprov1.getSelectedItem().toString();
        try{

            String sql="Insert into productos values ('"+idproducto+"','"+nombreprod+"','"+categoria+"','"+activo+"')";

            PreparedStatement pes=cn.prepareStatement(sql);
            pes.executeUpdate();

            JOptionPane.showMessageDialog(rootPane, "Insertados");
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
        
        try{

            String sql1="Insert into stock values ('"+proveedores+"','"+idproducto+"','"+cantidad+"','"+fecha+"','"+precio+"')";
            PreparedStatement pes1=cn.prepareStatement(sql1);

            pes1.executeUpdate();
            JOptionPane.showMessageDialog(rootPane, "Insertados");
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }//GEN-LAST:event_txtipanaderiaActionPerformed

    private void cmbprov1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbprov1ActionPerformed

    }//GEN-LAST:event_cmbprov1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    private void ImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImagenActionPerformed

    }//GEN-LAST:event_ImagenActionPerformed

    private void txtidprod0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidprod0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidprod0ActionPerformed

    private void btninventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninventarioActionPerformed
         Inventario prin = new  Inventario();
        prin.setVisible(true);
        this.hide();
    }//GEN-LAST:event_btninventarioActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       p4.setSelectedIndex(1);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        p4.setSelectedIndex(2);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        p4.setSelectedIndex(3);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtidprod3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidprod3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidprod3ActionPerformed

    private void Imagen3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Imagen3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Imagen3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void cmbprov4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbprov4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbprov4ActionPerformed

    private void txtipanaderia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtipanaderia1ActionPerformed
String dia = Integer.toString(txtfv3.getCalendar().get(Calendar.DAY_OF_MONTH));
        String mes = Integer.toString(txtfv3.getCalendar().get(Calendar.MONTH) + 1);
        String year = Integer.toString(txtfv3.getCalendar().get(Calendar.YEAR));
        String fecha = (dia + "/" + mes+ "/" + year);
        String cantidad=txtcant3.getValue().toString();
        String idproducto=txtidprod3.getText(),nombreprod=txtname3.getText();
        int categoria=0,activo=1;
        double precio=Double.parseDouble(txtprecio3.getText());
         String proveedores=cmbprov4.getSelectedItem().toString();
        try{

            String sql="Insert into ingredientes values ('"+idproducto+"','"+nombreprod+"','"+categoria+"','"+activo+"','"+cantidad+"','"+proveedores+"','"+fecha+"','"+precio+"')";

            PreparedStatement pes=cn.prepareStatement(sql);
            pes.executeUpdate();

            JOptionPane.showMessageDialog(rootPane, "Insertados");
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(rootPane, "NO Insertados");
        }        
    }//GEN-LAST:event_txtipanaderia1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bodega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bodega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bodega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bodega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bodega().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Imagen;
    private javax.swing.JTextField Imagen1;
    private javax.swing.JTextField Imagen2;
    private javax.swing.JTextField Imagen3;
    private javax.swing.JButton btninventario;
    private javax.swing.JButton btnsalir;
    private javax.swing.JComboBox<String> cmbprov1;
    private javax.swing.JComboBox<String> cmbprov2;
    private javax.swing.JComboBox<String> cmbprov3;
    private javax.swing.JComboBox<String> cmbprov4;
    private javax.swing.JLabel foto_panaderia;
    private javax.swing.JLabel foto_panaderia1;
    private javax.swing.JLabel foto_panaderia2;
    private javax.swing.JLabel foto_panaderia3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
<<<<<<< HEAD
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
=======
>>>>>>> a864b7f7262c6d1fbd52be3f45fcee6683907d89
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTabbedPane p4;
    private javax.swing.JPanel panel_alimento;
    private javax.swing.JPanel panel_panaderia;
    private javax.swing.JPanel panel_panaderia1;
    private javax.swing.JPanel panel_panaderia2;
    private javax.swing.JPanel panel_panaderia3;
    private javax.swing.JSpinner txtcant0;
    private javax.swing.JSpinner txtcant1;
    private javax.swing.JSpinner txtcant2;
    private javax.swing.JSpinner txtcant3;
    private com.toedter.calendar.JDateChooser txtfv0;
    private com.toedter.calendar.JDateChooser txtfv1;
    private com.toedter.calendar.JDateChooser txtfv2;
    private com.toedter.calendar.JDateChooser txtfv3;
    private javax.swing.JTextField txtidprod0;
    private javax.swing.JTextField txtidprod1;
    private javax.swing.JTextField txtidprod2;
    private javax.swing.JTextField txtidprod3;
    private javax.swing.JButton txtipanaderia;
    private javax.swing.JButton txtipanaderia1;
    private javax.swing.JButton txtlacteos;
    private javax.swing.JTextField txtname0;
    private javax.swing.JTextField txtname1;
    private javax.swing.JTextField txtname2;
    private javax.swing.JTextField txtname3;
    private javax.swing.JTextField txtprecio0;
    private javax.swing.JTextField txtprecio1;
    private javax.swing.JTextField txtprecio2;
    private javax.swing.JTextField txtprecio3;
    private javax.swing.JButton txttienda;
    // End of variables declaration//GEN-END:variables
}
