/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SeminarioForms;

import Servicios.conectar;
import entidades.Productos;
import entidades.Proveedores;
import entidades.stock;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Vector;

/**
 *
 * @author Usuario Dell
 */
public class Inventario extends javax.swing.JFrame {
DefaultTableModel tab=new DefaultTableModel();
    conectar cc=new conectar();
    Connection cn=cc.Conexionn();
    Productos prods=new Productos();
    stock prodss=new stock();
    Proveedores provs=new Proveedores();
    String proveedores="",proveedores2="",proveedores3="";
    
    /**
     * Creates new form Inventoarios
     */
    public Inventario() {
        initComponents();
        Cargar_P();
        Cargar_P2();
        Cargar_P3();
         this.setLocationRelativeTo(null);
         tab.addColumn("IdProducto");
        tab.addColumn("Nombre");
        tab.addColumn("Categoria");
        tab.addColumn("Proveedor");
        tab.addColumn("F_Vencimiento");
        tab.addColumn("Cantidad");
        tab.addColumn("Precio");
        
        mostrar.setModel(tab);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p4 = new javax.swing.JTabbedPane();
        panel_alimento = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        panel_panaderia = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtidprod0 = new javax.swing.JTextField();
        txtname0 = new javax.swing.JTextField();
        txtfv0 = new com.toedter.calendar.JDateChooser();
        foto_panaderia = new javax.swing.JLabel();
        Imagen = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        cmbprov1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtipanaderia = new javax.swing.JButton();
        txtcant0 = new javax.swing.JSpinner();
        jLabel20 = new javax.swing.JLabel();
        txtprecio0 = new javax.swing.JTextField();
        panel_lacteos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtfv1 = new com.toedter.calendar.JDateChooser();
        foto_lacteos = new javax.swing.JLabel();
        Imagen_lacteos = new javax.swing.JTextField();
        txtidpro1 = new javax.swing.JTextField();
        S_lacteos = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cmbprov2 = new javax.swing.JComboBox<>();
        txtilacteos = new javax.swing.JButton();
        txtname1 = new javax.swing.JTextField();
        txtcant1 = new javax.swing.JSpinner();
        jLabel21 = new javax.swing.JLabel();
        txtprecio1 = new javax.swing.JTextField();
        panel_tienda = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        foto_tienda = new javax.swing.JLabel();
        Imagen_Tienda = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cmbprov3 = new javax.swing.JComboBox<>();
        txtinserttienda = new javax.swing.JButton();
        txtidpro2 = new javax.swing.JTextField();
        txtname2 = new javax.swing.JTextField();
        txtcant2 = new javax.swing.JSpinner();
        txtfv2 = new com.toedter.calendar.JDateChooser();
        jLabel22 = new javax.swing.JLabel();
        txtprecio2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        mostrar = new javax.swing.JTable();
        btnsalir = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        txtcodpro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtnombrepro = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        descripcion = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        cmbregistro = new javax.swing.JComboBox<>();
        btnbuscar = new javax.swing.JButton();
        guardar2 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_alimento.setBackground(new java.awt.Color(204, 204, 204));
        panel_alimento.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Tipo de alimento"));

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jLabel10.setText("Tipo de alimento");

        javax.swing.GroupLayout panel_alimentoLayout = new javax.swing.GroupLayout(panel_alimento);
        panel_alimento.setLayout(panel_alimentoLayout);
        panel_alimentoLayout.setHorizontalGroup(
            panel_alimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_alimentoLayout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        panel_alimentoLayout.setVerticalGroup(
            panel_alimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_alimentoLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        p4.addTab("Seleccione uno", panel_alimento);

        panel_panaderia.setBackground(new java.awt.Color(204, 204, 204));
        panel_panaderia.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Panaderia"));
        panel_panaderia.setLayout(null);

        jLabel1.setText("Cantidad*:");
        panel_panaderia.add(jLabel1);
        jLabel1.setBounds(90, 150, 53, 20);

        jLabel11.setText("Idproducto*:");
        panel_panaderia.add(jLabel11);
        jLabel11.setBounds(80, 60, 80, 14);

        jLabel13.setText("Nombre*:");
        panel_panaderia.add(jLabel13);
        jLabel13.setBounds(100, 100, 60, 29);

        jLabel12.setText("Fecha de vencimiento* :");
        panel_panaderia.add(jLabel12);
        jLabel12.setBounds(40, 190, 151, 30);

        txtidprod0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidprod0ActionPerformed(evt);
            }
        });
        panel_panaderia.add(txtidprod0);
        txtidprod0.setBounds(180, 50, 120, 30);
        panel_panaderia.add(txtname0);
        txtname0.setBounds(180, 100, 120, 30);
        panel_panaderia.add(txtfv0);
        txtfv0.setBounds(190, 190, 140, 30);

        foto_panaderia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel_panaderia.add(foto_panaderia);
        foto_panaderia.setBounds(460, 50, 93, 87);

        Imagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImagenActionPerformed(evt);
            }
        });
        panel_panaderia.add(Imagen);
        Imagen.setBounds(460, 160, 90, 20);

        jButton1.setText("Seleccionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panel_panaderia.add(jButton1);
        jButton1.setBounds(450, 190, 110, 30);

        cmbprov1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        cmbprov1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbprov1ActionPerformed(evt);
            }
        });
        panel_panaderia.add(cmbprov1);
        cmbprov1.setBounds(190, 240, 180, 30);

        jLabel4.setText("Proveedor*:");
        panel_panaderia.add(jLabel4);
        jLabel4.setBounds(100, 250, 60, 14);

        txtipanaderia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Icono_nuevo.png"))); // NOI18N
        txtipanaderia.setText("Guardar");
        txtipanaderia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtipanaderiaActionPerformed(evt);
            }
        });
        panel_panaderia.add(txtipanaderia);
        txtipanaderia.setBounds(460, 270, 100, 40);
        panel_panaderia.add(txtcant0);
        txtcant0.setBounds(180, 150, 60, 20);

        jLabel20.setText("Precio*:");
        panel_panaderia.add(jLabel20);
        jLabel20.setBounds(100, 290, 39, 14);
        panel_panaderia.add(txtprecio0);
        txtprecio0.setBounds(180, 282, 110, 30);

        p4.addTab("Panadería", panel_panaderia);

        panel_lacteos.setBackground(new java.awt.Color(204, 204, 204));
        panel_lacteos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Lacteos"));

        jLabel2.setText("Cantidad* :");

        jLabel14.setText("Idproducto*:");

        jLabel15.setText("Nombre* :");

        jLabel16.setText("Fecha de vencimiento* :");

        foto_lacteos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtidpro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidpro1ActionPerformed(evt);
            }
        });

        S_lacteos.setText("Seleccionar");
        S_lacteos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S_lacteosActionPerformed(evt);
            }
        });

        jLabel5.setText("Proveedor*:");

        cmbprov2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        txtilacteos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Icono_nuevo.png"))); // NOI18N
        txtilacteos.setText("Guardar");
        txtilacteos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtilacteosActionPerformed(evt);
            }
        });

        jLabel21.setText("Precio*:");

        javax.swing.GroupLayout panel_lacteosLayout = new javax.swing.GroupLayout(panel_lacteos);
        panel_lacteos.setLayout(panel_lacteosLayout);
        panel_lacteosLayout.setHorizontalGroup(
            panel_lacteosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_lacteosLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(panel_lacteosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_lacteosLayout.createSequentialGroup()
                        .addGroup(panel_lacteosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panel_lacteosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_lacteosLayout.createSequentialGroup()
                                    .addGroup(panel_lacteosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel15)
                                        .addComponent(jLabel14))
                                    .addGap(41, 41, 41)
                                    .addGroup(panel_lacteosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtidpro1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtname1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(panel_lacteosLayout.createSequentialGroup()
                                    .addGap(12, 12, 12)
                                    .addComponent(jLabel2)))
                            .addGroup(panel_lacteosLayout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panel_lacteosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtcant1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtfv1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(panel_lacteosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_lacteosLayout.createSequentialGroup()
                                .addGap(190, 190, 190)
                                .addComponent(foto_lacteos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_lacteosLayout.createSequentialGroup()
                                .addGap(179, 179, 179)
                                .addGroup(panel_lacteosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(S_lacteos)
                                    .addComponent(Imagen_lacteos, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(panel_lacteosLayout.createSequentialGroup()
                        .addGroup(panel_lacteosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(panel_lacteosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_lacteosLayout.createSequentialGroup()
                                .addComponent(cmbprov2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(125, 125, 125)
                                .addComponent(txtilacteos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtprecio1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        panel_lacteosLayout.setVerticalGroup(
            panel_lacteosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_lacteosLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(panel_lacteosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_lacteosLayout.createSequentialGroup()
                        .addGroup(panel_lacteosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtidpro1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_lacteosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_lacteosLayout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(txtname1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel_lacteosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcant1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panel_lacteosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfv1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel_lacteosLayout.createSequentialGroup()
                        .addComponent(foto_lacteos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Imagen_lacteos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(S_lacteos)))
                .addGroup(panel_lacteosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_lacteosLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(txtilacteos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_lacteosLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(panel_lacteosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cmbprov2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(19, 19, 19)
                .addGroup(panel_lacteosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel21)
                    .addComponent(txtprecio1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        p4.addTab("Lacteos", panel_lacteos);

        panel_tienda.setBackground(new java.awt.Color(204, 204, 204));
        panel_tienda.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Tienda"));

        jLabel9.setText("Cantidad* :");

        jLabel17.setText("Idproducto*:");

        jLabel18.setText("Nombre* :");

        jLabel19.setText("Fecha de vencimiento* :");

        foto_tienda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton3.setText("Seleccionar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel6.setText("Proveedor*:");

        cmbprov3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        txtinserttienda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Icono_nuevo.png"))); // NOI18N
        txtinserttienda.setText("Guardar");
        txtinserttienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtinserttiendaActionPerformed(evt);
            }
        });

        txtidpro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidpro2ActionPerformed(evt);
            }
        });

        jLabel22.setText("Precio*:");

        javax.swing.GroupLayout panel_tiendaLayout = new javax.swing.GroupLayout(panel_tienda);
        panel_tienda.setLayout(panel_tiendaLayout);
        panel_tiendaLayout.setHorizontalGroup(
            panel_tiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_tiendaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_tiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel_tiendaLayout.createSequentialGroup()
                        .addGroup(panel_tiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(panel_tiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_tiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtname2, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                                .addComponent(txtidpro2))
                            .addComponent(txtcant2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(120, 120, 120)
                        .addGroup(panel_tiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_tiendaLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(Imagen_Tienda, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_tiendaLayout.createSequentialGroup()
                                .addComponent(foto_tienda, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9))))
                    .addGroup(panel_tiendaLayout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtfv2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(98, 98, 98))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_tiendaLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbprov3, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(txtinserttienda, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
            .addGroup(panel_tiendaLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addComponent(txtprecio2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_tiendaLayout.setVerticalGroup(
            panel_tiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_tiendaLayout.createSequentialGroup()
                .addGroup(panel_tiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_tiendaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(foto_tienda, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Imagen_Tienda, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_tiendaLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(panel_tiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_tiendaLayout.createSequentialGroup()
                                .addGroup(panel_tiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel17)
                                    .addComponent(txtidpro2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtname2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel_tiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcant2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)))
                .addGap(18, 18, 18)
                .addGroup(panel_tiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_tiendaLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(panel_tiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfv2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(panel_tiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cmbprov3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panel_tiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(txtprecio2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panel_tiendaLayout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(txtinserttienda, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(62, Short.MAX_VALUE))))
        );

        p4.addTab("Tienda", panel_tienda);

        mostrar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo de barra", "Codigo producto", "Nombre", "Categoria", "Marca", "Tamaño", "Tipo", "Caducidad", "Imagen", "Descripcion"
            }
        ));
        jScrollPane1.setViewportView(mostrar);

        btnsalir.setText("Salir");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        jLabel3.setText("Nombre del producto* :");

        jLabel7.setText("Codigo de producto* :");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Descripcion"));

        descripcion.setColumns(20);
        descripcion.setRows(5);
        descripcion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane2.setViewportView(descripcion);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel8.setText("Se registra en* :");

        cmbregistro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Panaderia", "Lacteos", "Tienda", " " }));
        cmbregistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbregistroActionPerformed(evt);
            }
        });

        btnbuscar.setText("Buscar");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(txtcodpro, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(txtnombrepro, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(cmbregistro, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtcodpro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtnombrepro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cmbregistro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Buscar Productos", jPanel2);

        guardar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Icono_nuevo.png"))); // NOI18N
        guardar2.setText("Guardar");
        guardar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardar2ActionPerformed(evt);
            }
        });

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menu_general12.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(p4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(guardar2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1050, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(720, 720, 720)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(441, 441, 441)
                .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 1060, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(p4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(guardar2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(470, 470, 470)
                .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void Cargar_P()
    {
        cmbprov1.removeAllItems();
       conectar cc=new conectar();
        Connection cn=cc.Conexionn();
        String  nitprov=provs.getNitproveedor(), nombreprov=provs.getNombreProveedor(), direccion=provs.getDirecion(),c1="";
        int telefono=provs.getTelefono(), activo=provs.getActivo();
            try
                {
                      String sql="select *from proveedores";
                      PreparedStatement pes=cn.prepareStatement(sql);
                      ResultSet raton=pes.executeQuery();
                      while(raton.next())
                      {
                          nitprov=raton.getString("Nitproveedor");nombreprov=raton.getString("NombreProveedor");telefono=raton.getInt("Telefono");direccion=raton.getString("Direccion");
                          proveedores=nitprov;
                          c1=""+nitprov+" "+nombreprov;
                           cmbprov1.addItem(c1);
                }
                }catch(Exception e){}
                
    }
public void Cargar_P2()
    {
        cmbprov2.removeAllItems();
       conectar cc=new conectar();
        Connection cn=cc.Conexionn();
        String nitprov=provs.getNitproveedor(), nombreprov=provs.getNombreProveedor(), direccion=provs.getDirecion(),c1="";
        int telefono=provs.getTelefono(), activo=provs.getActivo();
            try
                {
                      String sql="select *from proveedores";
                      PreparedStatement pes=cn.prepareStatement(sql);
                      ResultSet raton=pes.executeQuery();
                      while(raton.next())
                      {
                          nitprov=raton.getString("Nitproveedor");nombreprov=raton.getString("NombreProveedor");telefono=raton.getInt("Telefono");direccion=raton.getString("Direccion");
                          c1=""+nitprov+" "+nombreprov;
                          proveedores2=nitprov;
                           cmbprov2.addItem(c1);
                }
                }catch(Exception e){}
                
    }
public void Cargar_P3()
    {
        cmbprov3.removeAllItems();
       conectar cc=new conectar();
        Connection cn=cc.Conexionn();
        String nitprov=provs.getNitproveedor(), nombreprov=provs.getNombreProveedor(), direccion=provs.getDirecion(),c1="";
        int telefono=provs.getTelefono(), activo=provs.getActivo();
            try
                {
                      String sql="select *from proveedores";
                      PreparedStatement pes=cn.prepareStatement(sql);
                      ResultSet raton=pes.executeQuery();
                      while(raton.next())
                      {
                          nitprov=raton.getString("Nitproveedor");nombreprov=raton.getString("NombreProveedor");telefono=raton.getInt("Telefono");direccion=raton.getString("Direccion");
                          c1=""+nitprov+" "+nombreprov;
                          proveedores3=nitprov;
                           cmbprov3.addItem(c1);
                }
                }catch(Exception e){}
                
    }
    public void BuscarProductos()
{
    Vector dato=new Vector();
    
    String bus=txtcodpro.getText();
          String idproducto=prods.getIdprodycto();
                          String Nombre=prods.getNombre();
                          int categoria=prods.getCategoria();
                          int activo=prods.getActivo();
           String nitproveedor=prodss.getNitproveedor();
                          String F_vencimiento=prodss.getFechaVencimiento();
                          int cantidad=prodss.getCantidad();
                          double precio=prodss.getPrecio();
            try
                {
                      String sql="select *from productos where IdProducto='"+bus+"'";
                      String sql1="select *from stock where IdProducto='"+bus+"'";
                      PreparedStatement pes=cn.prepareStatement(sql);
                      PreparedStatement pes1=cn.prepareStatement(sql1);
                      ResultSet raton=pes.executeQuery();
                      
                      while(raton.next() )
                      {
                         
                          idproducto=raton.getString("IdProducto");
                          Nombre=raton.getString("Nombre");
                           categoria=raton.getInt("Categoria");
                           activo =raton.getInt("Activo");
                          
                          
                          if(categoria==0)
                          {
                             cmbregistro.setSelectedItem("Panaderia");
                          } else  if(categoria==1)
                          {
                              cmbregistro.setSelectedItem("Lacteos");
                          }else if(categoria==2)
                          {
                              cmbregistro.setSelectedItem("Tienda");
                          }
                         
                           
                          txtcodpro.setText(idproducto);
                          txtnombrepro.setText(Nombre);
                         descripcion.setText(String.valueOf(activo));
                         
                          
                          
                      }
                      ResultSet raton1=pes1.executeQuery();
                      while(raton1.next())
                      {
                         
                           nitproveedor=raton1.getString("NitProveedor");
                           cantidad=raton1.getInt("Cantidad");
                            F_vencimiento=raton1.getString("FechaVencimiento");
                           precio=raton1.getDouble("Precio");
                           
                      }
                      dato.addElement(idproducto);
                      dato.addElement(Nombre);
                      dato.addElement(categoria);
                      dato.addElement(nitproveedor);
                      dato.addElement(F_vencimiento);
                      dato.addElement(cantidad);
                      dato.addElement(precio);
                      tab.addRow(dato);
                      mostrar.setModel(tab);
                      
                }
            catch(Exception e)
                {
                        JOptionPane.showMessageDialog(rootPane, e);
                }
    
    
}
    
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtidprod0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidprod0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidprod0ActionPerformed

    private void ImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImagenActionPerformed

    }//GEN-LAST:event_ImagenActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void S_lacteosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S_lacteosActionPerformed
        
    }//GEN-LAST:event_S_lacteosActionPerformed

    private void txtipanaderiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtipanaderiaActionPerformed
        String dia = Integer.toString(txtfv0.getCalendar().get(Calendar.DAY_OF_MONTH));
String mes = Integer.toString(txtfv0.getCalendar().get(Calendar.MONTH) + 1);
String year = Integer.toString(txtfv0.getCalendar().get(Calendar.YEAR));
String fecha = (dia + "/" + mes+ "/" + year);
        String cantidad=txtcant0.getValue().toString();
       String idproducto=txtidprod0.getText(),nombreprod=txtname0.getText();
       int categoria=0,activo=1;
       double precio=Double.parseDouble(txtprecio0.getText());
        
        
        conectar cc=new conectar();
        Connection cn=cc.Conexionn();
        try{
            
            String sql="Insert into productos values ('"+idproducto+"','"+nombreprod+"','"+categoria+"','"+activo+"')";
            
            PreparedStatement pes=cn.prepareStatement(sql);
            pes.executeUpdate();
           
            JOptionPane.showMessageDialog(rootPane, "Insertados");
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(rootPane, "NO Insertados");
        }       
        try{
            
          
            String sql1="Insert into stock values ('"+proveedores+"','"+idproducto+"','"+cantidad+"','"+fecha+"','"+precio+"')";
            PreparedStatement pes1=cn.prepareStatement(sql1);
            
            pes1.executeUpdate();
            JOptionPane.showMessageDialog(rootPane, "Insertados");
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(rootPane, "NO Insertados");
        }       
    }//GEN-LAST:event_txtipanaderiaActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        Menu_administrador prin = new  Menu_administrador();
        prin.setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnsalirActionPerformed

    private void guardar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guardar2ActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
         BuscarProductos();
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void cmbregistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbregistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbregistroActionPerformed

    private void txtilacteosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtilacteosActionPerformed
    
            String dia = Integer.toString(txtfv1.getCalendar().get(Calendar.DAY_OF_MONTH));
String mes = Integer.toString(txtfv1.getCalendar().get(Calendar.MONTH) + 1);
String year = Integer.toString(txtfv1.getCalendar().get(Calendar.YEAR));
String fecha = (dia + "/" + mes+ "/" + year);
        String cantidad=txtcant1.getValue().toString();
       String idproducto=txtidpro1.getText(),nombreprod=txtname1.getText();
       int categoria=1,activo=1;
       double precio=Double.parseDouble(txtprecio1.getText());
        
        
        conectar cc=new conectar();
        Connection cn=cc.Conexionn();
        try{
            
            String sql="Insert into productos values ('"+idproducto+"','"+nombreprod+"','"+categoria+"','"+activo+"')";
            
            PreparedStatement pes=cn.prepareStatement(sql);
            pes.executeUpdate();
           
            JOptionPane.showMessageDialog(rootPane, "Insertados");
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(rootPane, "NO Insertados");
        }       
        try{
            
          
            String sql1="Insert into stock values ('"+proveedores2+"','"+idproducto+"','"+cantidad+"','"+fecha+"','"+precio+"')";
            PreparedStatement pes1=cn.prepareStatement(sql1);
            
            pes1.executeUpdate();
            JOptionPane.showMessageDialog(rootPane, "Insertados");
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(rootPane, "NO Insertados");
        }       
    }//GEN-LAST:event_txtilacteosActionPerformed

    private void txtinserttiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtinserttiendaActionPerformed
                  String dia = Integer.toString(txtfv2.getCalendar().get(Calendar.DAY_OF_MONTH));
String mes = Integer.toString(txtfv2.getCalendar().get(Calendar.MONTH) + 1);
String year = Integer.toString(txtfv2.getCalendar().get(Calendar.YEAR));
String fecha = (dia + "/" + mes+ "/" + year);
        String cantidad=txtcant2.getValue().toString();
       String idproducto=txtidpro2.getText(),nombreprod=txtname2.getText();
       int categoria=2,activo=1;
       double precio=Double.parseDouble(txtprecio2.getText());
        
        
        conectar cc=new conectar();
        Connection cn=cc.Conexionn();
        try{
            
            String sql="Insert into productos values ('"+idproducto+"','"+nombreprod+"','"+categoria+"','"+activo+"')";
            
            PreparedStatement pes=cn.prepareStatement(sql);
            pes.executeUpdate();
           
            JOptionPane.showMessageDialog(rootPane, "Insertados");
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(rootPane, "NO Insertados");
        }       
        try{
            
          
            String sql1="Insert into stock values ('"+proveedores3+"','"+idproducto+"','"+cantidad+"','"+fecha+"','"+precio+"')";
            PreparedStatement pes1=cn.prepareStatement(sql1);
            
            pes1.executeUpdate();
            JOptionPane.showMessageDialog(rootPane, "Insertados");
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(rootPane, "NO Insertados");
        } 
    }//GEN-LAST:event_txtinserttiendaActionPerformed

    private void cmbprov1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbprov1ActionPerformed
        
    }//GEN-LAST:event_cmbprov1ActionPerformed

    private void txtidpro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidpro1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidpro1ActionPerformed

    private void txtidpro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidpro2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidpro2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inventario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Imagen;
    private javax.swing.JTextField Imagen_Tienda;
    private javax.swing.JTextField Imagen_lacteos;
    private javax.swing.JButton S_lacteos;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btnsalir;
    private javax.swing.JComboBox<String> cmbprov1;
    private javax.swing.JComboBox<String> cmbprov2;
    private javax.swing.JComboBox<String> cmbprov3;
    private javax.swing.JComboBox<String> cmbregistro;
    private javax.swing.JTextArea descripcion;
    private javax.swing.JLabel foto_lacteos;
    private javax.swing.JLabel foto_panaderia;
    private javax.swing.JLabel foto_tienda;
    private javax.swing.JButton guardar2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable mostrar;
    private javax.swing.JTabbedPane p4;
    private javax.swing.JPanel panel_alimento;
    private javax.swing.JPanel panel_lacteos;
    private javax.swing.JPanel panel_panaderia;
    private javax.swing.JPanel panel_tienda;
    private javax.swing.JSpinner txtcant0;
    private javax.swing.JSpinner txtcant1;
    private javax.swing.JSpinner txtcant2;
    private javax.swing.JTextField txtcodpro;
    private com.toedter.calendar.JDateChooser txtfv0;
    private com.toedter.calendar.JDateChooser txtfv1;
    private com.toedter.calendar.JDateChooser txtfv2;
    private javax.swing.JTextField txtidpro1;
    private javax.swing.JTextField txtidpro2;
    private javax.swing.JTextField txtidprod0;
    private javax.swing.JButton txtilacteos;
    private javax.swing.JButton txtinserttienda;
    private javax.swing.JButton txtipanaderia;
    private javax.swing.JTextField txtname0;
    private javax.swing.JTextField txtname1;
    private javax.swing.JTextField txtname2;
    private javax.swing.JTextField txtnombrepro;
    private javax.swing.JTextField txtprecio0;
    private javax.swing.JTextField txtprecio1;
    private javax.swing.JTextField txtprecio2;
    // End of variables declaration//GEN-END:variables
}
