/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SeminarioForms;

/**
 *
 * @author Dylan
 */
public class Recetas extends javax.swing.JFrame {

    /**
     * Creates new form Recetas
     */
    public Recetas() {
        initComponents();
        this.setLocationRelativeTo(null);
         menu_crear.setVisible(false);
          menu_nuevo.setVisible(false);
         menu_creado.setVisible(false);
         menu_terminado.setVisible(false);
         
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        combo_recetas = new javax.swing.JComboBox<>();
        menu_crear = new javax.swing.JDesktopPane();
        combo_crear = new javax.swing.JComboBox<>();
        menu_nuevo = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nombreplato = new javax.swing.JTextField();
        combo_horario = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        comensales = new javax.swing.JTextField();
        precio_estimado = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        menu_ingredientes = new javax.swing.JDesktopPane();
        aceites = new javax.swing.JButton();
        lacteos = new javax.swing.JButton();
        verduras = new javax.swing.JButton();
        cereales = new javax.swing.JButton();
        Carnes = new javax.swing.JButton();
        Bebidas = new javax.swing.JButton();
        frutas = new javax.swing.JButton();
        Otros = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tiempo_preparacion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        valoracion = new javax.swing.JTextField();
        guardar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        imagen = new javax.swing.JButton();
        procedencia = new javax.swing.JButton();
        trucos = new javax.swing.JButton();
        preparacion = new javax.swing.JButton();
        codigo_receta = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        menu_creado = new javax.swing.JDesktopPane();
        jLabel13 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        codigo = new javax.swing.JTextField();
        nombre_receta = new javax.swing.JTextField();
        editar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        guardar_modificacion = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        crear_menu = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        menu_terminado = new javax.swing.JDesktopPane();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        combo_categoria = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        inventario = new javax.swing.JButton();
        vender = new javax.swing.JButton();
        menu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Recetas");

        combo_recetas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Crear", "Terminado" }));
        combo_recetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_recetasActionPerformed(evt);
            }
        });

        menu_crear.setBackground(new java.awt.Color(204, 204, 204));

        combo_crear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nuevo", "Creado" }));
        combo_crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_crearActionPerformed(evt);
            }
        });
        menu_crear.add(combo_crear);
        combo_crear.setBounds(850, 70, 110, 22);

        menu_nuevo.setBackground(new java.awt.Color(153, 153, 153));

        jLabel2.setText("Nombre del platillo :");
        menu_nuevo.add(jLabel2);
        jLabel2.setBounds(30, 60, 116, 16);

        jLabel3.setText("Horario :");
        menu_nuevo.add(jLabel3);
        jLabel3.setBounds(30, 110, 60, 16);
        menu_nuevo.add(nombreplato);
        nombreplato.setBounds(160, 60, 120, 22);

        combo_horario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Matutino ", "Vespertino" }));
        menu_nuevo.add(combo_horario);
        combo_horario.setBounds(120, 110, 90, 22);

        jLabel4.setText("Comensales :");
        menu_nuevo.add(jLabel4);
        jLabel4.setBounds(30, 310, 90, 16);
        menu_nuevo.add(comensales);
        comensales.setBounds(140, 310, 120, 22);
        menu_nuevo.add(precio_estimado);
        precio_estimado.setBounds(140, 340, 120, 22);

        jLabel5.setText("Precio estimado :");
        menu_nuevo.add(jLabel5);
        jLabel5.setBounds(30, 340, 110, 16);

        jLabel6.setText("Nuevo");
        menu_nuevo.add(jLabel6);
        jLabel6.setBounds(410, 20, 41, 16);

        aceites.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/aceites.jpg"))); // NOI18N
        aceites.setText("jButton1");
        aceites.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceitesActionPerformed(evt);
            }
        });
        menu_ingredientes.add(aceites);
        aceites.setBounds(0, 0, 140, 70);

        lacteos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lacteos.jpg"))); // NOI18N
        lacteos.setText("jButton1");
        lacteos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lacteosActionPerformed(evt);
            }
        });
        menu_ingredientes.add(lacteos);
        lacteos.setBounds(140, 0, 140, 70);

        verduras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/verduras.jpg"))); // NOI18N
        verduras.setText("jButton1");
        verduras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verdurasActionPerformed(evt);
            }
        });
        menu_ingredientes.add(verduras);
        verduras.setBounds(280, 0, 140, 70);

        cereales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cereales.jpg"))); // NOI18N
        cereales.setText("jButton1");
        cereales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerealesActionPerformed(evt);
            }
        });
        menu_ingredientes.add(cereales);
        cereales.setBounds(0, 70, 140, 70);

        Carnes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carnes.jpg"))); // NOI18N
        Carnes.setText("jButton1");
        Carnes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarnesActionPerformed(evt);
            }
        });
        menu_ingredientes.add(Carnes);
        Carnes.setBounds(140, 70, 140, 70);

        Bebidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bebidas.jpg"))); // NOI18N
        Bebidas.setText("jButton1");
        Bebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BebidasActionPerformed(evt);
            }
        });
        menu_ingredientes.add(Bebidas);
        Bebidas.setBounds(280, 70, 140, 70);

        frutas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/frutas.jpg"))); // NOI18N
        frutas.setText("jButton1");
        frutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frutasActionPerformed(evt);
            }
        });
        menu_ingredientes.add(frutas);
        frutas.setBounds(420, 0, 140, 70);

        Otros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/otros.jpg"))); // NOI18N
        Otros.setText("jButton1");
        Otros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OtrosActionPerformed(evt);
            }
        });
        menu_ingredientes.add(Otros);
        Otros.setBounds(420, 70, 140, 70);

        menu_nuevo.add(menu_ingredientes);
        menu_ingredientes.setBounds(350, 240, 560, 140);

        jLabel7.setText("Ingredientes");
        menu_nuevo.add(jLabel7);
        jLabel7.setBounds(590, 220, 80, 16);

        jLabel8.setText("Tiempo de preparacion :");
        menu_nuevo.add(jLabel8);
        jLabel8.setBounds(30, 260, 150, 16);
        menu_nuevo.add(tiempo_preparacion);
        tiempo_preparacion.setBounds(190, 260, 110, 22);

        jLabel9.setText("Valoracion :");
        menu_nuevo.add(jLabel9);
        jLabel9.setBounds(30, 370, 80, 16);
        menu_nuevo.add(valoracion);
        valoracion.setBounds(140, 370, 120, 22);

        guardar.setText("Guardar");
        menu_nuevo.add(guardar);
        guardar.setBounds(660, 390, 79, 25);

        cancelar.setText("Cancelar");
        menu_nuevo.add(cancelar);
        cancelar.setBounds(750, 390, 90, 25);

        jButton5.setText("Nuevo");
        menu_nuevo.add(jButton5);
        jButton5.setBounds(860, 390, 67, 25);

        jLabel14.setText("Temporada :");
        menu_nuevo.add(jLabel14);
        jLabel14.setBounds(310, 120, 75, 16);

        jCheckBox1.setText("Primavera");
        menu_nuevo.add(jCheckBox1);
        jCheckBox1.setBounds(400, 120, 87, 25);

        jCheckBox2.setText("Verano");
        menu_nuevo.add(jCheckBox2);
        jCheckBox2.setBounds(500, 120, 69, 25);

        jCheckBox3.setText("Otoño");
        menu_nuevo.add(jCheckBox3);
        jCheckBox3.setBounds(580, 120, 63, 25);

        jCheckBox4.setText("Invierno");
        menu_nuevo.add(jCheckBox4);
        jCheckBox4.setBounds(660, 120, 75, 25);

        jLabel15.setText("Dificultad :");
        menu_nuevo.add(jLabel15);
        jLabel15.setBounds(310, 170, 70, 16);

        jLabel16.setText("Calorias :");
        menu_nuevo.add(jLabel16);
        jLabel16.setBounds(30, 170, 55, 16);

        jRadioButton1.setText("Sencillo");
        menu_nuevo.add(jRadioButton1);
        jRadioButton1.setBounds(400, 170, 73, 25);

        jRadioButton2.setText("Media");
        menu_nuevo.add(jRadioButton2);
        jRadioButton2.setBounds(500, 170, 107, 25);

        jRadioButton3.setText("Dificil");
        menu_nuevo.add(jRadioButton3);
        jRadioButton3.setBounds(620, 170, 59, 25);

        jRadioButton4.setText("Bajo");
        menu_nuevo.add(jRadioButton4);
        jRadioButton4.setBounds(110, 170, 107, 25);

        jRadioButton5.setText("Medio");
        menu_nuevo.add(jRadioButton5);
        jRadioButton5.setBounds(110, 200, 63, 25);

        jRadioButton6.setText("Alto");
        menu_nuevo.add(jRadioButton6);
        jRadioButton6.setBounds(110, 230, 51, 25);

        jLabel17.setText("Categoria :");
        menu_nuevo.add(jLabel17);
        jLabel17.setBounds(310, 80, 70, 16);

        jRadioButton7.setText("Entrada");
        menu_nuevo.add(jRadioButton7);
        jRadioButton7.setBounds(400, 80, 80, 25);

        jRadioButton8.setText("Primer Plato");
        menu_nuevo.add(jRadioButton8);
        jRadioButton8.setBounds(490, 80, 99, 25);

        jRadioButton9.setText("Segundo Plato");
        menu_nuevo.add(jRadioButton9);
        jRadioButton9.setBounds(610, 80, 111, 25);

        jRadioButton10.setText("Postre");
        menu_nuevo.add(jRadioButton10);
        jRadioButton10.setBounds(730, 80, 65, 25);

        jRadioButton11.setText("Dulce");
        menu_nuevo.add(jRadioButton11);
        jRadioButton11.setBounds(800, 80, 59, 25);

        imagen.setText("I.");
        imagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imagenActionPerformed(evt);
            }
        });
        menu_nuevo.add(imagen);
        imagen.setBounds(890, 150, 50, 50);

        procedencia.setText("P.");
        procedencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procedenciaActionPerformed(evt);
            }
        });
        menu_nuevo.add(procedencia);
        procedencia.setBounds(890, 100, 50, 50);

        trucos.setText("T.");
        trucos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trucosActionPerformed(evt);
            }
        });
        menu_nuevo.add(trucos);
        trucos.setBounds(890, 50, 50, 50);

        preparacion.setText("P.");
        preparacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preparacionActionPerformed(evt);
            }
        });
        menu_nuevo.add(preparacion);
        preparacion.setBounds(890, 0, 50, 50);
        menu_nuevo.add(codigo_receta);
        codigo_receta.setBounds(540, 50, 120, 22);

        jLabel22.setText("Código :");
        menu_nuevo.add(jLabel22);
        jLabel22.setBounds(470, 50, 48, 16);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/123.jpg"))); // NOI18N
        menu_nuevo.add(jLabel11);
        jLabel11.setBounds(-70, -220, 1160, 740);

        menu_crear.add(menu_nuevo);
        menu_nuevo.setBounds(50, 120, 940, 430);

        menu_creado.setBackground(new java.awt.Color(153, 153, 153));

        jLabel13.setText("Recetas");
        menu_creado.add(jLabel13);
        jLabel13.setBounds(420, 20, 60, 16);

        jLabel18.setText("Código :");
        menu_creado.add(jLabel18);
        jLabel18.setBounds(40, 80, 48, 16);

        jLabel19.setText("Receta :");
        menu_creado.add(jLabel19);
        jLabel19.setBounds(40, 140, 60, 16);
        menu_creado.add(codigo);
        codigo.setBounds(120, 80, 140, 22);
        menu_creado.add(nombre_receta);
        nombre_receta.setBounds(120, 140, 140, 22);

        editar.setText("Editar");
        menu_creado.add(editar);
        editar.setBounds(670, 380, 65, 25);

        eliminar.setText("Eliminar");
        menu_creado.add(eliminar);
        eliminar.setBounds(750, 380, 79, 25);

        guardar_modificacion.setText("Guardar");
        menu_creado.add(guardar_modificacion);
        guardar_modificacion.setBounds(840, 380, 79, 25);

        jLabel12.setText("jLabel12");
        menu_creado.add(jLabel12);
        jLabel12.setBounds(570, 60, 310, 250);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/123.jpg"))); // NOI18N
        menu_creado.add(jLabel20);
        jLabel20.setBounds(0, 0, 940, 430);

        menu_crear.add(menu_creado);
        menu_creado.setBounds(50, 120, 940, 430);

        jLabel10.setText("Crear");
        menu_crear.add(jLabel10);
        jLabel10.setBounds(470, 30, 40, 16);

        crear_menu.setText("Crear menu");
        menu_crear.add(crear_menu);
        crear_menu.setBounds(790, 680, 101, 25);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menu_general12.jpg"))); // NOI18N
        menu_crear.add(jLabel21);
        jLabel21.setBounds(-20, -100, 1160, 740);

        menu_terminado.setBackground(new java.awt.Color(204, 204, 204));

        jLabel23.setText("Terminado");
        menu_terminado.add(jLabel23);
        jLabel23.setBounds(460, 30, 62, 16);

        jLabel24.setText("Código :");
        menu_terminado.add(jLabel24);
        jLabel24.setBounds(40, 80, 48, 16);

        jLabel25.setText("Receta :");
        menu_terminado.add(jLabel25);
        jLabel25.setBounds(40, 150, 48, 16);

        jLabel26.setText("jLabel26");
        menu_terminado.add(jLabel26);
        jLabel26.setBounds(590, 80, 340, 270);
        menu_terminado.add(jTextField1);
        jTextField1.setBounds(130, 80, 100, 22);
        menu_terminado.add(jTextField2);
        jTextField2.setBounds(130, 150, 100, 22);

        jLabel27.setText("Agregar cantidad :");
        menu_terminado.add(jLabel27);
        jLabel27.setBounds(50, 310, 110, 16);
        menu_terminado.add(jTextField3);
        jTextField3.setBounds(190, 310, 140, 22);

        jButton1.setText("Aceptar");
        menu_terminado.add(jButton1);
        jButton1.setBounds(810, 500, 77, 25);

        jButton2.setText("Cancelar");
        menu_terminado.add(jButton2);
        jButton2.setBounds(910, 500, 90, 25);

        jLabel29.setText("Categoria :");
        menu_terminado.add(jLabel29);
        jLabel29.setBounds(40, 210, 70, 16);

        combo_categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Desayunos", "Almuerzos", "Bebidas Frias", "Bebidas Calientes", "Postres" }));
        menu_terminado.add(combo_categoria);
        combo_categoria.setBounds(160, 210, 130, 22);

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/123.jpg"))); // NOI18N
        menu_terminado.add(jLabel28);
        jLabel28.setBounds(0, 0, 1020, 570);

        inventario.setText("Inventario");

        vender.setText("Vender");

        menu.setText("Menu");
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(490, 490, 490)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(900, 900, 900)
                        .addComponent(combo_recetas, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(menu_terminado, javax.swing.GroupLayout.PREFERRED_SIZE, 1020, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(menu_crear, javax.swing.GroupLayout.PREFERRED_SIZE, 1020, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(810, 810, 810)
                        .addComponent(inventario)
                        .addGap(11, 11, 11)
                        .addComponent(menu)
                        .addGap(17, 17, 17)
                        .addComponent(vender, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addComponent(combo_recetas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menu_terminado, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menu_crear, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inventario)
                    .addComponent(menu)
                    .addComponent(vender))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aceitesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceitesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aceitesActionPerformed

    private void lacteosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lacteosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lacteosActionPerformed

    private void verdurasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verdurasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_verdurasActionPerformed

    private void cerealesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerealesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cerealesActionPerformed

    private void CarnesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarnesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CarnesActionPerformed

    private void BebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BebidasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BebidasActionPerformed

    private void frutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frutasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_frutasActionPerformed

    private void OtrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OtrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OtrosActionPerformed

    private void combo_recetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_recetasActionPerformed
          String valor = (String)combo_recetas.getSelectedItem();
        if (valor.equals("Crear")){
            menu_crear.setVisible(true);  
             menu_terminado.setVisible(false);
        }if (valor.equals("Terminado")){
            menu_crear.setVisible(false);  
             menu_terminado.setVisible(true);
        }
    }//GEN-LAST:event_combo_recetasActionPerformed

    private void combo_crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_crearActionPerformed
        String valor = (String)combo_crear.getSelectedItem();
        if (valor.equals("Nuevo")){
            menu_nuevo.setVisible(true); 
            menu_creado.setVisible(false); 
        }
        if (valor.equals("Creado")){
            menu_creado.setVisible(true); 
            menu_nuevo.setVisible(false); 
        }
    }//GEN-LAST:event_combo_crearActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
    

    }//GEN-LAST:event_menuActionPerformed

    private void preparacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preparacionActionPerformed
         Procedimiento prin = new Procedimiento();
            prin.setVisible(true);
            this.hide(); 
    }//GEN-LAST:event_preparacionActionPerformed

    private void trucosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trucosActionPerformed
         Trucos prin = new Trucos();
            prin.setVisible(true);
            this.hide(); 
    }//GEN-LAST:event_trucosActionPerformed

    private void procedenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procedenciaActionPerformed
         
    }//GEN-LAST:event_procedenciaActionPerformed

    private void imagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imagenActionPerformed
        
    }//GEN-LAST:event_imagenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Recetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Recetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Recetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Recetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Recetas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bebidas;
    private javax.swing.JButton Carnes;
    private javax.swing.JButton Otros;
    private javax.swing.JButton aceites;
    private javax.swing.JButton cancelar;
    private javax.swing.JButton cereales;
    private javax.swing.JTextField codigo;
    private javax.swing.JTextField codigo_receta;
    private javax.swing.JComboBox<String> combo_categoria;
    private javax.swing.JComboBox<String> combo_crear;
    private javax.swing.JComboBox<String> combo_horario;
    private javax.swing.JComboBox<String> combo_recetas;
    private javax.swing.JTextField comensales;
    private javax.swing.JButton crear_menu;
    private javax.swing.JButton editar;
    private javax.swing.JButton eliminar;
    private javax.swing.JButton frutas;
    private javax.swing.JButton guardar;
    private javax.swing.JButton guardar_modificacion;
    private javax.swing.JButton imagen;
    private javax.swing.JButton inventario;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton lacteos;
    private javax.swing.JButton menu;
    private javax.swing.JDesktopPane menu_creado;
    private javax.swing.JDesktopPane menu_crear;
    private javax.swing.JDesktopPane menu_ingredientes;
    private javax.swing.JDesktopPane menu_nuevo;
    private javax.swing.JDesktopPane menu_terminado;
    private javax.swing.JTextField nombre_receta;
    private javax.swing.JTextField nombreplato;
    private javax.swing.JTextField precio_estimado;
    private javax.swing.JButton preparacion;
    private javax.swing.JButton procedencia;
    private javax.swing.JTextField tiempo_preparacion;
    private javax.swing.JButton trucos;
    private javax.swing.JTextField valoracion;
    private javax.swing.JButton vender;
    private javax.swing.JButton verduras;
    // End of variables declaration//GEN-END:variables
}
